=== Alexandru93s/proiectweb/medic.dtd
<!ELEMENT medic (id, nume, specializare, telefon, email, cas, programari)>
<!ELEMENT id (#PCDATA)>
<!ELEMENT nume (#PCDATA)>
<!ELEMENT specializare (#PCDATA)>
<!ELEMENT telefon (#PCDATA)>
<!ELEMENT email (#PCDATA)>
<!ELEMENT cas (#PCDATA)>

<!ELEMENT programari (programare*)>
<!ELEMENT programare (data, ora, pacient)>
<!ELEMENT data (#PCDATA)>
<!ELEMENT ora (#PCDATA)>

<!ELEMENT pacient (nume, cnp, telefon)>
<!ELEMENT cnp (#PCDATA)>

=== Alexandru93s/proiectweb/medic.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE medic SYSTEM "medic.dtd">
<medic>
    <id>123</id>
    <nume>Dr. Andrei Popescu</nume>
    <specializare>Cardiologie</specializare>
    <telefon>0723-456-789</telefon>
    <email>andrei.popescu@clinica.ro</email>
    <cas>true</cas>
    
    <programari>
        <programare>
            <data>2025-06-01</data>
            <ora>10:00</ora>
            <pacient>
                <nume>Maria Ionescu</nume>
                <cnp>2890512345678</cnp>
                <telefon>0744-123-456</telefon>
            </pacient>
        </programare>
    </programari>
</medic>
